global:
  scrape_interval: '60s'
  evaluation_interval: '60s'

scrape_configs:
  - job_name: 'staging-tracking-service'
    metrics_path: /monitoring/metrics
    # Add the api key to the GET params.
    params:
      api_key: ['TRACKING_SERVICE_API_KEY']
    static_configs:
      - targets: ['staging-tracking-service:8000']
  - job_name: 'staging-predictor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['staging-predictor-nginx:80']
  - job_name: 'staging-stack-monitor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['stack-monitor-nginx:80']
  - job_name: 'staging-prediction-service'
    static_configs:
      - targets: ['prediction-service:8000']
  - job_name: 'staging-prediction-monitor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['prediction-monitor-nginx:80']
  - job_name: 'node' # 'node' is Required by dashboard
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'staging-biker-swarm-monitor'
    metrics_path: /crashReports/metrics
    # Add the api key to the GET params.
    params:
      api_key: ['BIKER_SWARM_MONITOR_API_KEY']
    static_configs:
      - targets: ['staging-biker-swarm-monitor:8000']
  - job_name: 'staging-load-service'
    metrics_path: /monitoring/metrics
    # Add the api key to the GET params.
    params:
      api_key: ['LOAD_SERVICE_API_KEY']
    static_configs:
      - targets: ['staging-load-service:8000']
