global:
  scrape_interval: '60s'
  evaluation_interval: '60s'

scrape_configs:
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'node-exporter'
      type: 'A'
      port: 9100
  - job_name: 'tracking-service'
    metrics_path: /monitoring/metrics
    # Add the api key to the GET params.
    params:
      api_key: ['TRACKING_SERVICE_API_KEY']
    static_configs:
      - targets: ['tracking-service-manager:8000']
  - job_name: 'predictor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['predictor-nginx:80']
  - job_name: 'stack-monitor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['stack-monitor-nginx:80']
  - job_name: 'prediction-service'
    static_configs:
      - targets: ['prediction-service:8000']
  - job_name: 'prediction-monitor-nginx'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['prediction-monitor-nginx:80']
  - job_name: 'load-service'
    metrics_path: /metrics.txt
    static_configs:
      - targets: ['load-service-manager:80']
  - job_name: 'traefik-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8080']